# 워크플로 이름
name: Build Windows Executable (Ultimate)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python 3.8 버전 유지
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file from secret safely
        shell: python
        run: |
          import os, json
          credentials_json_string = os.environ.get('GOOGLE_CREDENTIALS')
          if not credentials_json_string: raise ValueError("GOOGLE_CREDENTIALS secret is not set.")
          try: json.loads(credentials_json_string)
          except: raise ValueError("Secret is not valid JSON.")
          with open('serene-exchange-438319-r7-1dc9aac8b9cf.json', 'w', encoding='utf-8') as f:
            f.write(credentials_json_string)
          print("Credentials file created successfully.")
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      # --- ▼▼▼ [최종 수정] hidden-import를 더 강력한 --collect-all로 교체 ▼▼▼ ---
      - name: Build single file executable with ultimate settings
        run: |
          pyinstaller --onefile `
            --name "TouristAnalyzer" `
            --windowed `
            --add-data "config.ini;." `
            --add-data "serene-exchange-438319-r7-1dc9aac8b9cf.json;." `
            --add-data "my_review_classifier;my_review_classifier" `
            # --- AI 관련 라이브러리들을 통째로 포함시켜 모듈 누락 문제를 원천 차단 ---
            --collect-all "transformers" `
            --collect-all "sentence_transformers" `
            --collect-all "tokenizers" `
            --collect-all "safetensors" `
            # --- Scikit-learn은 여전히 hidden-import가 더 효율적일 수 있음 ---
            --hidden-import "sklearn.utils._cython_blas" `
            --hidden-import "sklearn.neighbors._typedefs" `
            --hidden-import "sklearn.neighbors._quad_tree" `
            --hidden-import "sklearn.tree" `
            --hidden-import "sklearn.tree._utils" `
            main_app.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: TouristAnalyzer-Windows
          path: dist/TouristAnalyzer.exe
