# 워크플로 이름
name: Build Windows Executable (Comprehensive)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python 3.8 버전을 유지합니다. (단, 개발 환경과 동일하게 맞추는 것이 가장 안정적입니다.)
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file from secret safely
        shell: python
        run: |
          import os, json
          credentials_json_string = os.environ.get('GOOGLE_CREDENTIALS')
          if not credentials_json_string: raise ValueError("GOOGLE_CREDENTIALS secret is not set.")
          try: json.loads(credentials_json_string)
          except: raise ValueError("Secret is not valid JSON.")
          with open('serene-exchange-438319-r7-1dc9aac8b9cf.json', 'w', encoding='utf-8') as f:
            f.write(credentials_json_string)
          print("Credentials file created successfully.")
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      # --- ▼▼▼ [핵심 수정] PyInstaller 빌드 명령어에 포괄적인 hidden-import 추가 ▼▼▼ ---
      - name: Build single file executable with comprehensive settings
        run: |
          pyinstaller --onefile `
            --name "TouristAnalyzer" `
            --windowed `
            --add-data "config.ini;." `
            --add-data "serene-exchange-438319-r7-1dc9aac8b9cf.json;." `
            --add-data "my_review_classifier;my_review_classifier" `
            # --- Transformers 및 관련 모델 ---
            --hidden-import "transformers.models" `
            --hidden-import "transformers.pipelines" `
            --hidden-import "transformers.models.auto.modeling_auto" `
            --hidden-import "transformers.models.bert.modeling_bert" `
            --hidden-import "tokenizers.decoders" `
            --hidden-import "tokenizers.pre_tokenizers" `
            --hidden-import "tokenizers.processors" `
            # --- Sentence Transformers ---
            --hidden-import "sentence_transformers.models" `
            --hidden-import "sentence_transformers.util" `
            --hidden-import "sentence_transformers.cross_encoder" `
            --hidden-import "sentence_transformers.quantization" `
            # --- Scikit-learn 및 유틸리티 ---
            --hidden-import "sklearn" `
            --hidden-import "sklearn.utils._cython_blas" `
            --hidden-import "sklearn.neighbors._typedefs" `
            --hidden-import "sklearn.neighbors._quad_tree" `
            --hidden-import "sklearn.tree" `
            --hidden-import "sklearn.tree._utils" `
            # --- PyTorch 및 기타 백엔드 ---
            --hidden-import "torch" `
            --hidden-import "torch._C" `
            --hidden-import "safetensors" `
            --hidden-import "scipy.special.cython_special" `
            main_app.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: TouristAnalyzer-Windows
          path: dist/TouristAnalyzer.exe
